[package]
name = "repochecker"
description = "TODO"
license = "MIT OR Apache-2.0"

publish = false

version = "0.0.0-dev"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = []
keywords = []
#repository = ""

[dependencies]
#diesel = { version = "^1.4", features = ["sqlite"] }
reqwest = { version = "^0.10", features = ["blocking", "json"] }
retry = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^0.2", features = ["macros", "rt-core"] }
toml = "0.5.6"
#url = "^2.1"
warp = "^0.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

