[repochecker]
# refresh interval for repository data and package maintainers
interval = 4

[[release]]
# official name / releasever
name = "rawhide"
# repository configuration
type = "rawhide"
# available architectures
arches = ["x86_64", "aarch64", "armv7hl", "ppc64le", "s390x"]

[[release]]
# official name / releasever
name = "32"
# repository configuration
type = "stable"
# available architectures
arches = ["x86_64", "aarch64", "armv7hl", "ppc64le", "s390x"]

[[release]]
# official name / releasever
name = "31"
# repository configuration
type = "stable"
# available architectures
arches = ["x86_64", "aarch64", "armv7hl", "ppc64le", "s390x"]

[repos]
# stable releases + prereleases
stable = ["fedora", "fedora-source"]
# stable release updates
updates = ["updates", "updates-source"]
# stable release and prerelease testing updates
testing = ["updates-testing", "updates-testing-source"]
# rawhide repositories
rawhide = ["rawhide", "rawhide-source"]

[[arch]]
name = "x86_64"
# x86_64 is the only real "multiarch" architecture (with i686)
multiarch = ["x86_64", "noarch", "src", "i686"]

[[arch]]
name = "i686"
multiarch = ["i686", "noarch", "src"]

[[arch]]
name = "aarch64"
multiarch = ["aarch64", "noarch", "src"]

[[arch]]
name = "armv7hl"
multiarch = ["armv7hl", "noarch", "src"]

[[arch]]
name = "ppc64le"
multiarch = ["ppc64le", "noarch", "src"]

[[arch]]
name = "s390x"
multiarch = ["s390x", "noarch", "src"]

